apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumebackupproviders.backups.example.com
spec:
  group: backups.example.com
  names:
    kind: VolumeBackupProvider
    listKind: VolumeBackupProviderList
    plural: volumebackupproviders
    singular: volumebackupprovider
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bucketName:
              type: string
            providerType:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file'
              type: string
          required:
          - providerType
          - bucketName
          type: object
        status:
          properties:
            backupProviders:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file'
              items:
                type: object
              type: array
          required:
          - backupProviders
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
