apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-restore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backup-restore-operator
  template:
    metadata:
      labels:
        name: backup-restore-operator
    spec:
      serviceAccountName: backup-restore-operator
      containers:
        - name: backup-restore-operator
          # Replace this with the built image name
          image: 	172.30.1.1:5000/stateful-application/backup-restore-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - backup-restore-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "backup-restore-operator"
